# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html
#llm:
#  api_type: "moonshot"  # or azure / ollama / groq etc.
#  base_url: "https://api.moonshot.cn/v1"  # or forward url / other llm url
#  api_key: 
#  model: 'moonshot-v1-8k'

#llm:
#  api_type: "openai"  # or azure / ollama / groq etc.
#  base_url: "https://api.openai.com/v1/chat/completions"
#  api_key: 
#  model: "gpt-3.5-turbo"  # or gpt-3.5-turbo
#  proxy: "https://api.ddaiai.com/v1/chat/completions"  # for LLM API requests
#  # timeout: 600 # Optional. If set to 0, default value is 300.
#  # Details: https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service/
##  pricing_plan: "" # Optional. Use for Azure LLM when its model name is not the same as OpenAI's

llm:
  api_type: 'zhipuai'
  api_key: ''
  model: 'GLM-4'

  search:
    api_type: 'serpapi' # serpapi/google/serper/ddg
    api_key: ''
    # cse_id: 'YOUR_CSE_ID' # only for google
    params:
      engine: 'google' # google/bing/yahoo/baidu/yandex, check https://serpapi.com/bing-search-api for more details
      google_domain: 'google.com'
      gl: us
      hl: en
